const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const SHOW_MODAL = 'SHOW_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
const CONNECT_SOCKET_IO = 'CONNECT_SOCKET_IO';
const CONNECT_PUSHER = 'CONNECT_PUSHER';
const SEND_EVENT_WEBSOCKET = 'SEND_EVENT_WEBSOCKET';
const SEND_EVENT_SOCKET_IO = 'SEND_EVENT_SOCKET_IO';
const SEND_EVENT_PUSHER = 'SEND_EVENT_PUSHER';
const RECEIVE_EVENT_WEBSOCKET = 'RECEIVE_EVENT_WEBSOCKET';
const RECEIVE_EVENT_SOCKET_IO = 'RECEIVE_EVENT_SOCKET_IO';
const RECEIVE_EVENT_PUSHER = 'RECEIVE_EVENT_PUSHER';

export {
  CHANGE_LANGUAGE,
  SHOW_MODAL,
  CLOSE_MODAL,
  START_LOADING,
  STOP_LOADING,
  CONNECT_WEBSOCKET,
  CONNECT_SOCKET_IO,
  CONNECT_PUSHER,
  SEND_EVENT_WEBSOCKET,
  SEND_EVENT_SOCKET_IO,
  SEND_EVENT_PUSHER,
  RECEIVE_EVENT_WEBSOCKET,
  RECEIVE_EVENT_SOCKET_IO,
  RECEIVE_EVENT_PUSHER,
};
